# Generated by Django 4.2.26 on 2025-11-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
