# Generated by Django 4.2.26 on 2026-01-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_order_email_order_shipping_address1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anon_token", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="productlike",
            constraint=models.UniqueConstraint(
                fields=("product", "anon_token"), name="uniq_like_per_anon"
            ),
        ),
    ]
